# -*- coding: utf-8 -*-
"""brain_tumor_code_final[xai]1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPmuYct3LG7ReJzkMplAxXabVNGSEH3G
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile
with zipfile.ZipFile("/content/brain_tumor_dataset.zip", mode='r') as archive:
  archive.extractall()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve, precision_recall_curve, f1_score, auc

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, Flatten, Attention
from tensorflow.keras.metrics import BinaryAccuracy, Recall, Precision
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Clear any existing session to prevent memory leaks
tf.keras.backend.clear_session()

# Load the dataset from a directory
data = keras.utils.image_dataset_from_directory("/content/brain_tumor_dataset",label_mode='binary',  # Assuming binary classification (0 for no tumor, 1 for tumor)
    image_size=(256, 256),  # Image dimensions
    batch_size=32,          # Batch size for training
)

# Display a few sample images from the dataset
# Fetch the first batch to visualize
batch = data.as_numpy_iterator().next()

# Create a plot to display sample images
fig, ax = plt.subplots(3, 5, figsize=(15, 10))
ax = ax.flatten()  # Flatten axes for easier indexing

# Display the first 15 images with corresponding labels
for idx, img in enumerate(batch[0][:15]):
    ax[idx].imshow(img.astype(int))  # Ensure consistent data type (convert to int for display)
    ax[idx].set_title(f"Label: {int(batch[1][idx])}")  # Show corresponding label
    ax[idx].axis("off")  # Hide axis ticks

plt.show()  # Display the plot with sample images

# Normalize the data to scale images between 0 and 1
data = data.map(lambda x, y: (x / 255, y))  # Normalize images for consistency

# Verify the scaled data with a sample batch
scaled_batch = data.as_numpy_iterator().next()  # Get the next batch to check scaling
print("Min value:", scaled_batch[0].min())  # Check minimum value
print("Max value:", scaled_batch[0].max())  # Check maximum value

# Determine the dataset sizes for training, validation, and testing
total_batches = len(data)  # Total number of batches in the dataset
train_size = int(total_batches * 0.6)
val_size = int(total_batches * 0.2) + 1  # Add 1 to ensure no data is lost
test_size = int(total_batches * 0.2) + 1

print("Train Size:", train_size)  # Size for the training set
print("Validation Size:", val_size)  # Size for the validation set
print("Test Size:", test_size)  # Size for the test set

# Split the dataset into training, validation, and testing sets
train = data.take(train_size)  # First part for training
val = data.skip(train_size).take(val_size)  # Middle part for validation
test = data.skip(train_size + val_size).take(test_size)  # Last part for testing

# Define a deep learning model using a pre-trained ResNet-50 as the base
base_model = ResNet50(weights="imagenet", include_top=False, input_shape=(256, 256, 3))

# Freeze the base model's layers to retain pre-trained weights
for layer in base_model.layers:
    layer.trainable = False  # This prevents changing the pre-trained layers

# Add additional layers for the new task
attention = Attention()([base_model.output, base_model.output])  # Attention layer
flat = Flatten()(attention)  # Flatten the output for dense layers
dense1 = Dense(128, activation="relu")(flat)  # Dense layer with ReLU activation
output = Dense(1, activation="sigmoid")(dense1)  # Final output with sigmoid activation for binary classification

# Build the final model
model = keras.Model(inputs=base_model.input, outputs=output)  # Define the full model

# Compile the model with optimizer, loss function, and metrics
model.compile(optimizer=Adam(), loss=keras.losses.BinaryCrossentropy(), metrics=["accuracy"])  # Use Adam optimizer and binary crossentropy

model.summary()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve, precision_recall_curve, f1_score, auc
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, Flatten, Attention, Reshape
from tensorflow.keras.optimizers import Adam

# Load the dataset
data = keras.utils.image_dataset_from_directory(
    "/content/brain_tumor_dataset",
    label_mode='binary',
    image_size=(256, 256),
    batch_size=32,
)
data = data.map(lambda x, y: (x / 255, y))

# Split the dataset into training, validation, and testing sets
total_batches = len(data)
train_size = int(total_batches * 0.6)
val_size = int(total_batches * 0.2) + 1
test_size = int(total_batches * 0.2) + 1

train = data.take(train_size)
val = data.skip(train_size).take(val_size)
test = data.skip(train_size + val_size).take(test_size)

# Define the model using ResNet50 as the base
base_model = ResNet50(weights="imagenet", include_top=False, input_shape=(256, 256, 3))
for layer in base_model.layers:
    layer.trainable = False

# Reshape the output of ResNet50 to match the Attention layer's expected input
reshaped_output = Reshape((-1, base_model.output.shape[-1]))(base_model.output)

# Apply the Attention layer
attention_output = Attention()([reshaped_output, reshaped_output])

# Flatten and add dense layers
flat = Flatten()(attention_output)
dense1 = Dense(128, activation="relu")(flat)
output = Dense(1, activation="sigmoid")(dense1)

# Build and compile the model
model = keras.Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(), loss=keras.losses.BinaryCrossentropy(), metrics=["accuracy"])

# Train the model
history = model.fit(train, epochs=35, validation_data=val)

# Plot the training history
fig, ax = plt.subplots(2, 1, figsize=(10, 8))

ax[0].plot(history.history["loss"], label="Train")
ax[0].plot(history.history["val_loss"], label="Validation")
ax[0].set_title("Loss")
ax[0].legend()

ax[1].plot(history.history["accuracy"], label="Train")
ax[1].plot(history.history["val_accuracy"], label="Validation")
ax[1].set_title("Accuracy")
ax[1].legend()

plt.show()

from sklearn.metrics import f1_score, roc_auc_score, roc_curve, precision_recall_curve
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.metrics import BinaryAccuracy, Recall, Precision

# Assuming you have a test dataset named 'test' and a model named 'model'

bin_acc = BinaryAccuracy()
recall = Recall()
precision = Precision()

y_true_list = []
y_pred_list = []

for batch in test.as_numpy_iterator():
    X, y = batch
    yhat = model.predict(X)
    bin_acc.update_state(y, yhat)
    recall.update_state(y, yhat)
    precision.update_state(y, yhat)

    y_true_list.append(y)
    y_pred_list.append(yhat)

y_true = np.concatenate(y_true_list, axis=0)
y_pred = np.concatenate(y_pred_list, axis=0)

# Calculate F1 Score
f1 = f1_score(y_true, (y_pred > 0.5).astype(int))

# Calculate ROC-AUC score
roc_auc = roc_auc_score(y_true, y_pred)

# Calculate ROC curve
fpr, tpr, _ = roc_curve(y_true, y_pred)

# Calculate precision-recall curve
precision_curve, recall_curve, _ = precision_recall_curve(y_true, y_pred)

# Print all metrics
print("Accuracy:", bin_acc.result().numpy())
print("Recall:", recall.result().numpy())
print("Precision:", precision.result().numpy())
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guessing')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()

import lime
import lime.lime_image
import numpy as np
import matplotlib.pyplot as plt
from skimage.segmentation import mark_boundaries

# Function to make predictions for LIME
def predict_fn(images):
    """Return probabilities from the model."""
    # Normalize the images to [0, 1]
    images = images / 255
    predictions = model.predict(images)
    # Return probabilities and ensure correct shape for LIME
    return np.array([[1 - p[0], p[0]] for p in predictions])

# Create an explainer object for LIME
explainer = lime.lime_image.LimeImageExplainer()

# Get a sample image from the test dataset
sample_batch = test.as_numpy_iterator().next()
sample_image = sample_batch[0][0]  # First image from the batch
sample_label = sample_batch[1][0]  # Corresponding label

# Generate an explanation for the sample image
explanation = explainer.explain_instance(
    sample_image.astype('double'),  # Convert to double for LIME
    predict_fn,  # Prediction function for LIME
    top_labels=1,  # Number of top labels to explain
    hide_color=0,  # Color for hidden regions
    num_samples=1000,  # Number of perturbed samples
)

# Get the explanation for the top label
top_label = explanation.top_labels[0]  # Top predicted label
temp, mask = explanation.get_image_and_mask(
    top_label,
    positive_only=True,
    num_features=10,
    hide_rest=True
)

# Display the original image and the LIME explanation
fig, ax = plt.subplots(1, 2, figsize=(12, 6))

# Original image with label
ax[0].imshow(sample_image.astype(int))
ax[0].set_title(f"Original Image - Label: {int(sample_label)}")
ax[0].axis("off")

# LIME explanation with highlighted regions
ax[1].imshow(mark_boundaries(temp, mask))
ax[1].set_title("LIME Explanation - Positive Regions")
ax[1].axis("off")

plt.show()

import lime
import lime.lime_image
import numpy as np
import matplotlib.pyplot as plt
from skimage.segmentation import mark_boundaries

# Create an explainer object for LIME
explainer = lime.lime_image.LimeImageExplainer()

# Function to make predictions for LIME
def predict_fn(images):
    """Return probabilities from the model."""
    images = images / 255  # Normalize images to [0, 1]
    predictions = model.predict(images)
    # Return probabilities and ensure correct shape for LIME
    return np.array([[1 - p[0], p[0]] for p in predictions])

# Get a different sample image from the test dataset
sample_batch = test.as_numpy_iterator().next()  # Get a batch
sample_image = sample_batch[0][1]  # Take the second image from the batch
sample_label = sample_batch[1][1]  # Corresponding label

# Generate a LIME explanation for this new sample image
explanation = explainer.explain_instance(
    sample_image.astype('double'),  # Convert to double for LIME
    predict_fn,  # Prediction function for LIME
    top_labels=1,  # Number of top labels to explain
    hide_color=0,  # Color for hidden regions
    num_samples=1000  # Number of perturbed samples
)

# Get the explanation for the top label
top_label = explanation.top_labels[0]  # Top predicted label
temp, mask = explanation.get_image_and_mask(
    top_label,
    positive_only=True,
    num_features=10,
    hide_rest=True
)

# Display the original image and the LIME explanation for this new image
fig, ax = plt.subplots(1, 2, figsize=(12, 6))

# Original image with label
ax[0].imshow(sample_image.astype(int))  # Ensure data type is int for display
ax[0].set_title(f"Original Image - Label: {int(sample_label)}")
ax[0].axis("off")

# LIME explanation with highlighted regions
ax[1].imshow(mark_boundaries(temp, mask))
ax[1].set_title("LIME Explanation - Positive Regions")
ax[1].axis("off")

plt.show()

"""REST NET 50 NO ATTENTION"""

import cv2
import os
import numpy as np
import glob
import tensorflow as tf
from sklearn.metrics import confusion_matrix, precision_score, recall_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

# Load the model
model = load_model("brain_tumor_resnet_no_attention.h5")

# Load test data
# Assuming x_test, y_test are already defined

# Make predictions
y_pred = model.predict(x_test)
y_pred_binary = np.round(y_pred).flatten()

# Calculate evaluation metrics
accuracy = np.mean(y_pred_binary == y_test)
conf_matrix = confusion_matrix(y_test, y_pred_binary)
precision = precision_score(y_test, y_pred_binary)
recall = recall_score(y_test, y_pred_binary)
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred)

# Print evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("AUC:", auc)

# Plot ROC curve
plt.figure()
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

"""# CNN"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Load the dataset
data = keras.utils.image_dataset_from_directory('/content/brain_tumor_dataset')

# Display sample images from the dataset
batch = data.as_numpy_iterator().next()
fig, ax = plt.subplots(3, 5, figsize=(15, 10))
ax = ax.flatten()
for idx, img in enumerate(batch[0][:15]):
    ax[idx].imshow(img.astype(int))
    ax[idx].title.set_text(batch[1][idx])

# Normalize and split the dataset
data = data.map(lambda x, y: (x / 255, y))
train_size = int(len(data) * 0.6)
val_size = int(len(data) * 0.2) + 1
test_size = int(len(data) * 0.2) + 1
train = data.take(train_size)
val = data.skip(train_size).take(val_size)
test = data.skip(train_size + val_size).take(test_size)

# Data augmentation
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical", input_shape=(256, 256, 3)),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1),
    layers.RandomRotation(0.2)
])

# Display augmented images
plt.figure(figsize=(10, 10))
for i in range(9):
    augmented_image = data_augmentation(batch[0][0:1])  # Assuming `batch[0][0:1]` is an image
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(augmented_image[0].numpy().astype("uint8"))
    plt.axis("off")

# Define the model
model = keras.Sequential([
    data_augmentation,
    layers.Conv2D(16, (3, 3), 1, activation="relu", padding="same"),
    layers.Conv2D(16, (3, 3), 1, activation="relu", padding="same"),
    layers.MaxPooling2D(),
    layers.Conv2D(32, (5, 5), 1, activation="relu", padding="same"),
    layers.Conv2D(32, (5, 5), 1, activation="relu", padding="same"),
    layers.MaxPooling2D(),
    layers.Conv2D(16, (3, 3), 1, activation="relu", padding="same"),
    layers.Conv2D(16, (3, 3), 1, activation="relu", padding="same"),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

# Compile the model
model.compile(optimizer="adam", loss=keras.losses.BinaryCrossentropy(), metrics=["accuracy"])

# Train the model
history = model.fit(train, epochs=15, validation_data=val)

# Visualize training history
plt.figure(figsize=(10, 8))
plt.plot(history.history["loss"], label="Train")
plt.plot(history.history["val_loss"], label="Validation")
plt.title("Loss")
plt.legend()

plt.figure(figsize=(10, 8))
plt.plot(history.history["accuracy"], label="Train")
plt.plot(history.history["val_accuracy"], label="Validation")
plt.title("Accuracy")
plt.legend()

# Evaluate the model
bin_acc = keras.metrics.BinaryAccuracy()
recall = keras.metrics.Recall()
precision = keras.metrics.Precision()
y_true_list = []
y_pred_list = []

for batch in test.as_numpy_iterator():
    X, y = batch
    yhat = model.predict(X)
    bin_acc.update_state(y, yhat)
    recall.update_state(y, yhat)
    precision.update_state(y, yhat)

    y_true_list.append(y)
    y_pred_list.append(yhat)

y_true = np.concatenate(y_true_list, axis=0)
y_pred = np.concatenate(y_pred_list, axis=0)

roc_auc = roc_auc_score(y_true, y_pred)
fpr, tpr, _ = roc_curve(y_true, y_pred)

# Print evaluation metrics
print("Accuracy:", bin_acc.result().numpy())
print("Recall:", recall.result().numpy())
print("Precision:", precision.result().numpy())
print("F1 Score:", f1_score(y_true, (y_pred > 0.5).astype(int)))
print("ROC-AUC Score:", roc_auc)

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guessing')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()

# Calculate True Positive (TP), True Negative (TN), False Positive (FP), False Negative (FN)
TP = np.sum((y_true == 1) & (y_pred > 0.5))
TN = np.sum((y_true == 0) & (y_pred <= 0.5))
FP = np.sum((y_true == 0) & (y_pred > 0.5))
FN = np.sum((y_true == 1) & (y_pred <= 0.5))

# Calculate Sensitivity and Specificity
sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)

print("Sensitivity:", sensitivity)
print("Specificity:", specificity)

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Calculate Confusion Matrix
cm = confusion_matrix(y_true, (y_pred > 0.5))

# Plot Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', annot_kws={"size": 16})
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.show()

"""# VGG--19"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, roc_auc_score, roc_curve, confusion_matrix, classification_report
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.applications import VGG19
from tensorflow.keras.callbacks import EarlyStopping

# Load the dataset
data = keras.utils.image_dataset_from_directory('/content/brain_tumor_dataset')

# Divide the dataset into train, validation, and test sets
train_size = int(len(data) * 0.6)
val_size = int(len(data) * 0.2) + 1
test_size = int(len(data) * 0.2) + 1

train = data.take(train_size)
val = data.skip(train_size).take(val_size)
test = data.skip(train_size + val_size).take(test_size)

# Define the VGG-19 model
base_model = VGG19(weights='imagenet', include_top=False, input_shape=(256, 256, 3))

# Freeze the layers of the base model
for layer in base_model.layers:
    layer.trainable = False

# Add custom classification layers on top of the base model
model = Sequential([
    base_model,
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(train, epochs=15, validation_data=val)

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

# Predictions
y_true_list = []
y_pred_list = []

for batch in test.as_numpy_iterator():
    X, y = batch
    yhat = model.predict(X)
    y_true_list.append(y)
    y_pred_list.append(yhat)

y_true = np.concatenate(y_true_list, axis=0)
y_pred = np.concatenate(y_pred_list, axis=0)

# Calculate metrics
f1 = f1_score(y_true, (y_pred > 0.5).astype(int))
roc_auc = roc_auc_score(y_true, y_pred)

# Print metrics
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

# Calculate confusion matrix
cm = confusion_matrix(y_true, (y_pred > 0.5).astype(int))

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', annot_kws={"size": 16})
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.show()

import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import matplotlib.pyplot as plt

# Load a pre-trained VGG16 model
model = VGG16(weights='imagenet')

# Load and preprocess an image
img_path = '/content/brain_tumor_dataset/yes/Y1.jpg'  # Replace with the path to your image
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Get the top predicted class
preds = model.predict(x)
predicted_class = np.argmax(preds[0])
pred_class_name = decode_predictions(preds)[0][0][1]

# Get the output tensor of the last convolutional layer
last_conv_layer = model.get_layer('block5_conv3')

# Create a model that maps the input image to the activations of the last conv layer as well as the output predictions
grad_model = tf.keras.models.Model([model.inputs], [last_conv_layer.output, model.output])

# Compute the gradient of the top predicted class with respect to the output feature map of the last conv layer
with tf.GradientTape() as tape:
    conv_outputs, predictions = grad_model(x)
    loss = predictions[:, predicted_class]

grads = tape.gradient(loss, conv_outputs)[0]

# Compute the CAM
cam = np.mean(conv_outputs[0], axis=-1)
cam = np.maximum(cam, 0)
cam = cv2.resize(cam, (224, 224))
cam = cam / cam.max()

# Generate heatmap overlay
heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

# Superimpose the heatmap on the original image
superimposed_img = cv2.addWeighted(
    cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB).astype('float32'), 0.6,
    heatmap.astype('float32'), 0.4, 0
)
# Plot the original image, Grad-CAM heatmap, and the superimposed image
plt.figure(figsize=(12, 6))
plt.subplot(131)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB))

plt.subplot(132)
plt.title(f'Grad-CAM Heatmap ({pred_class_name})')
plt.imshow(heatmap)

plt.subplot(133)
plt.title(f'Superimposed Image ({pred_class_name})')
plt.imshow(superimposed_img)
plt.show()

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import matplotlib.pyplot as plt

# Load a pre-trained VGG16 model
model = VGG16(weights='imagenet')

# Load and preprocess an image
img_path = '/content/brain_tumor_dataset/yes/Y19.JPG'  # Replace with the path to your image
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Get the top predicted class
preds = model.predict(x)
predicted_class = np.argmax(preds[0])
pred_class_name = decode_predictions(preds)[0][0][1]

# Get the output tensor of the last convolutional layer
last_conv_layer = model.get_layer('block5_conv3')

# Create a model that maps the input image to the activations of the last conv layer as well as the output predictions
grad_model = tf.keras.models.Model([model.inputs], [last_conv_layer.output, model.output])

# Compute the gradient of the top predicted class with respect to the output feature map of the last conv layer
with tf.GradientTape() as tape:
    conv_outputs, predictions = grad_model(x)
    loss = predictions[:, predicted_class]

grads = tape.gradient(loss, conv_outputs)[0]

# Compute the CAM
cam = np.mean(conv_outputs[0], axis=-1)
cam = np.maximum(cam, 0)
cam = cv2.resize(cam, (224, 224))
cam = cam / cam.max()

# Generate heatmap overlay
heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

# Superimpose the heatmap on the original image
superimposed_img = cv2.addWeighted(
    cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB).astype('float32'), 0.6,
    heatmap.astype('float32'), 0.4, 0
)
# Plot the original image, Grad-CAM heatmap, and the superimposed image
plt.figure(figsize=(12, 6))
plt.subplot(131)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB))

plt.subplot(132)
plt.title(f'Grad-CAM Heatmap ({pred_class_name})')
plt.imshow(heatmap)

plt.subplot(133)
plt.title(f'Superimposed Image ({pred_class_name})')
plt.imshow(superimposed_img)
plt.show()

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import matplotlib.pyplot as plt

# Load a pre-trained VGG16 model
model = VGG16(weights='imagenet')

# Load and preprocess an image
img_path = '/content/brain_tumor_dataset/yes/Y66.JPG'  # Replace with the path to your image
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Get the top predicted class
preds = model.predict(x)
predicted_class = np.argmax(preds[0])
pred_class_name = decode_predictions(preds)[0][0][1]

# Get the output tensor of the last convolutional layer
last_conv_layer = model.get_layer('block5_conv3')

# Create a model that maps the input image to the activations of the last conv layer as well as the output predictions
grad_model = tf.keras.models.Model([model.inputs], [last_conv_layer.output, model.output])

# Compute the gradient of the top predicted class with respect to the output feature map of the last conv layer
with tf.GradientTape() as tape:
    conv_outputs, predictions = grad_model(x)
    loss = predictions[:, predicted_class]

grads = tape.gradient(loss, conv_outputs)[0]

# Compute the CAM
cam = np.mean(conv_outputs[0], axis=-1)
cam = np.maximum(cam, 0)
cam = cv2.resize(cam, (224, 224))
cam = cam / cam.max()

# Generate heatmap overlay
heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

# Superimpose the heatmap on the original image
superimposed_img = cv2.addWeighted(
    cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB).astype('float32'), 0.6,
    heatmap.astype('float32'), 0.4, 0
)
# Plot the original image, Grad-CAM heatmap, and the superimposed image
plt.figure(figsize=(12, 6))
plt.subplot(131)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(x[0], cv2.COLOR_BGR2RGB))

plt.subplot(132)
plt.title(f'Grad-CAM Heatmap ({pred_class_name})')
plt.imshow(heatmap)

plt.subplot(133)
plt.title(f'Superimposed Image ({pred_class_name})')
plt.imshow(superimposed_img)
plt.show()

